name: Windows MSYS

on:
  push:
    tags:
      - '*'  # Triggers on any tag push
env:
  NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - target_arch: x86_64
           compiler: clang
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}
      COMPILER: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          ccache
          clang
          cmake
          git
          make
          pkgconf
          python3
          mingw-w64-${{ matrix.target_arch }}-binutils
          mingw-w64-${{ matrix.target_arch }}-ccache
          mingw-w64-${{ matrix.target_arch }}-clang
          mingw-w64-${{ matrix.target_arch }}-cmake
          mingw-w64-${{ matrix.target_arch }}-ffmpeg
          mingw-w64-${{ matrix.target_arch }}-pkgconf
          mingw-w64-${{ matrix.target_arch }}-qt6
          mingw-w64-${{ matrix.target_arch }}-vlc

    - name: Release Build
      run: ./ports/ci/windows-msys/build.sh
    - name: Release Deploy
      run: ./ports/ci/windows-msys/deploy.sh
    - name: Release Upload
      uses: softprops/action-gh-release@v1
      with:
        repository: beliaev-maksim/webcamoid-windows-build
        files: |
          webcamoid-packages/windows-gcc-x86_64/*
          webcamoid-packages/windows-gcc-i686/*


